### ISSUE TITLE
Enum serialisation and deserialisation is not complementary

### ISSUE THREAD

**Issue by anuraags** [timbod7/adl#33]
I'm not sure if complementary is the word here (invertible maybe?)

If I declare a union such as this:
```
union GraphType {
  Void area;
  Void line;
  Void zones;
  Void onoff;
};
struct Foo {
   GraphType graphType;
};
```

It reads it in from json as for example `"graphType": "area"`

but when it serialises back to json it becomes
```
"graphType": {
   "disc": "AREA"
}
```

It seems like serialisation and deserialisation should be the reverse of each other?

**Comment by anuraags** [comment]
I see that this is probably an artefact of using unions to define enums?

**Comment by timbod7** [comment]
No. This should definite work as you expect - ie the data should "round trip" through the serialisation. Seems like a bug.

But... T=there's something strange about your serialised data:

```
"graphType": {
   "disc": "AREA"
}
```

Did you perhaps use gson to serialise the java object, rather than calling the ADL generated serialisation code?

**Comment by anuraags** [comment]
Hmmmm....this is in the context of a http response. So I just return the adl generated object and let the http server work out the serialisation by itself. And I believe you're right, the http server does indeed use gson for the serialisation.

So you think I should first calle `object.jsonBinding().toJson()` before returning?

**Comment by timbod7** [comment]
Yes. You should be calling `object.jsonBinding().toJson()` to generage the json.

These two function:

    MyClass.jsonBinding().toJson(...)
    MyClass.jsonBinding().fromJson(...)

should be inverses. However, there are (by design) not consistent with the json produced by

Gson gson = new GsonBuilder().create();
gson.toJson(...);

There's a few reasons for this: gson doesn't support generics easily, it's json isn't necessarily consistent with that produced by libraries for other languages etc.

It may be possible to create gson type adapters so that gson can generate ADL compatible json for ADL objects.

**Comment by timbod7** [comment]
Not an ADL issue...
